### ISSUE TITLE
DEMO_PDM_RECORD_PLAYBACK-MONO

### ISSUE THREAD

**Issue by Aztec02** [dialog-semiconductor/BLE_SDK10_examples#13]
I run the DEMO_PDM_RECORD_PLAYBACK but want to record **MONO** pdm data and play **MONO** pcm data on the codec.
I am trying to do this by defining AUDIO_CHANNEL_MONO in the structs in audio_task.c (see attached image)
![Capture](https://user-images.githubusercontent.com/87807998/126659515-ab8a5dac-e1e5-4247-8528-53231ab00e91.PNG)

Everything is built correctly and the demo starts but when I press the button to start recording the code gets stuck in 
qspi_check_and_suspend_operations(); (see attached image)
![Capture2](https://user-images.githubusercontent.com/87807998/126660031-b74d47fb-595f-40b1-b8d5-4b97f04bb45a.PNG)

problem is solved if in "static audio_quality_t _memory_recording" I leave the channels as AUDIO_CHANNEL_STEREO but I do not think that this is the correct way.

Also, have defined "prepare_pdm(&_audio.pdm_in, AUDIO_CHANNEL_MONO);" inside audio_task.

Is there something I am missing?

**Comment by kalamara** [comment]
Hello,
Τo record PDM mono you should change
in audio_task.c:audio_task() (line 325):
prepare_pdm(&_audio.pdm_in, AUDIO_CHANNEL_STEREO); =>  
prepare_pdm(&_audio.pdm_in, AUDIO_CHANNEL_MONO);

The _codec_mic struct  is for  configuration of the analog microphones that are coming from the CODEC.
The PDM interface is a separate interface on the DA14690 where you can directly 
connect your digital microphones. There is no special configuration struct for it because the only thing there is to configure is whether it is STEREO or MONO.

However even in the way you have implemented it now  there is no harm done, i think.

I hope this helps
